version: '3'
services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./www:/var/www/
    container_name: d-nginx
    networks:
      - backend
  php:
    build: ./php/
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/log:/var/log/
    container_name: d-php
    networks:
      - backend
networks:
  backend:
    driver: bridge