version: '3'
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    depends_on: 
      - php
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./www:/var/www/
    container_name: d-nginx
    networks:
      - backend
  php:
    build: ./php/
    volumes:
      - ./www:/var/www
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/log:/var/log/
    container_name: d-php
    networks:
      - backend
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
     - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql-files:/var/lib/mysql-files
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    container_name: d-mysql
    restart: always
    networks:
      - backend
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    restart: always
    container_name: d-redis
    networks:
      - backend
networks:
  backend:
    driver: bridge